name: Extract CapCut Classes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  extract:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download CapCut
      run: |
        echo "🚀 جاري التحميل المباشر..."
        curl -L -o CapCut.zip "https://store1.gofile.io/download/direct/s3Pnil/CapCut.zip"

    - name: Unzip IPA File
      run: |
        echo "📦 جاري فك الضغط..."
        unzip -q CapCut.zip -d extracted_files
        APP_PATH=$(find extracted_files -name "*.app" | head -n 1)
        echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

    - name: Install dsdump (Class Dump Tool)
      run: |
        echo "🛠️ جاري تحميل أداة dsdump..."
        curl -L -o dsdump.tar.gz https://github.com/DerekSelander/dsdump/releases/download/v0.0.4/dsdump.tar.gz
        tar -xzf dsdump.tar.gz
        chmod +x dsdump
        sudo mv dsdump /usr/local/bin/

    - name: Extract Classes and Hooks
      run: |
        echo "🔍 جاري استخراج الكلاسات..."
        # البحث عن الملف التنفيذي
        EXECUTABLE_PATH=$(find ${{ env.APP_PATH }} -maxdepth 1 -type f -exec file {} \; | grep "Mach-O" | cut -d: -f1 | head -n 1)
        dsdump --objc $EXECUTABLE_PATH > CapCut_Classes.txt
        echo "✅ تم الاستخراج بنجاح!"

    - name: Upload Classes File to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CapCut-Class-Dump
        path: CapCut_Classes.txt
